title: Savvas Savvides, Ph.D.
subtitle: Software Engineer
#subtitle: Senior Software Engineer, Fortanix
#subtitle2: Scientific Collaborator, European University Cyprus (EUC)
#subtitle3: Adjunct Researcher, Università della Svizzera italiana (USI)
description: >- # this means to ignore newlines until "baseurl:"

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
- text: About
  url: /
- text: Blog
  url: /blog
- text: Publications
  url: /publications
#- text: Gallery
#  url: /gallery


# Author details

author: Savvas Savvides
author_logo: profile.png
# author_email: "savvas [at] fortanix [dot] com"
# author_location: Mountain View, California
author_location: Nicosia, Cyprus
author_website_url: "https://ssavvides.github.io/"

# social links
twitter_username: sa_savvides
github_username: ssavvides
#facebook_username: johndoe
linkedin_username: ssavvides
#behance_username: johndoe
#instagram_username: johndoe
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# pagination of posts
paginate: 5
# per_page: 4
paginate_path: "/blog/page/:num/"

collections:
  category:
    output: true

defaults:
  - scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  - scope:
      type: categories
    values:
      layout: category_index
      permalink: categories/:category/

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
#  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
